#!/usr/bin/env python3
"""
Compute Dice score overlaps between attention maps from different foundation models.

This script analyzes attention maps generated by the extract_attention_maps.py script
and computes Dice score overlaps between every pair of the 5 foundation models:
- MUSK
- CONCH v1.5  
- Virchow2
- H-optimus1
- GigaPath

The script supports two modes:
1. Fixed threshold mode: Uses a fixed threshold (default: 0.5) to binarize attention maps
2. Percentile mode: Uses percentile-based thresholding (default: 50th, 60th, 70th, 80th, 90th percentiles)

The script outputs:
1. A CSV file with Dice scores for all model pairs
2. Heatmap visualizations of the overlap scores
3. 5 random example tiles with attention map overlays for each model (saved as PNG files)

Usage:
    # Fixed threshold mode
    python compute_attention_overlap.py --parent-folder /path/to/parent/folder --threshold 0.5
    
    # Percentile mode (recommended)
    python compute_attention_overlap.py --parent-folder /path/to/parent/folder --percentile-mode --percentiles 50.0 60.0 70.0 80.0 90.0
    
    # Simple mode (for attention maps from --simple flag in extract_attention_maps.py)
    python compute_attention_overlap.py --parent-folder /path/to/parent/folder --percentile-mode --simple
"""

import argparse
import csv
import random
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import itertools

import numpy as np
from PIL import Image, ImageFilter
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.colors import Normalize
import seaborn as sns
from tqdm import tqdm
from scipy import ndimage

# Set random seed for reproducible results
random.seed(42)
np.random.seed(42)


def dice_score_percentile(mask1: np.ndarray, mask2: np.ndarray, percentile: float = 50.0) -> float:
    """
    Compute Dice score between two binary masks using percentile-based thresholding.
    
    Args:
        mask1: First attention map (0-1 normalized)
        mask2: Second attention map (0-1 normalized) 
        percentile: Percentile to use for thresholding (e.g., 50.0 for 50th percentile)
        
    Returns:
        Dice score between 0 and 1
    """
    # Calculate percentile thresholds for each mask
    threshold1 = np.percentile(mask1, percentile)
    threshold2 = np.percentile(mask2, percentile)
    
    # Convert to binary masks using percentile thresholds
    binary1 = (mask1 >= threshold1).astype(np.uint8)
    binary2 = (mask2 >= threshold2).astype(np.uint8)
    
    # Compute intersection and union
    intersection = np.logical_and(binary1, binary2).sum()
    union = binary1.sum() + binary2.sum()
    
    # Avoid division by zero
    if union == 0:
        return 1.0 if intersection == 0 else 0.0
    
    # Dice score = 2 * intersection / union
    dice = 2.0 * intersection / union
    return dice


def dice_score(mask1: np.ndarray, mask2: np.ndarray, threshold: float = 0.5) -> float:
    """
    Compute Dice score between two binary masks using fixed threshold.
    
    Args:
        mask1: First attention map (0-1 normalized)
        mask2: Second attention map (0-1 normalized) 
        threshold: Threshold to convert to binary masks (default: 0.5)
        
    Returns:
        Dice score between 0 and 1
    """
    # Convert to binary masks using threshold
    binary1 = (mask1 >= threshold).astype(np.uint8)
    binary2 = (mask2 >= threshold).astype(np.uint8)
    
    # Compute intersection and union
    intersection = np.logical_and(binary1, binary2).sum()
    union = binary1.sum() + binary2.sum()
    
    # Avoid division by zero
    if union == 0:
        return 1.0 if intersection == 0 else 0.0
    
    # Dice score = 2 * intersection / union
    dice = 2.0 * intersection / union
    return dice


def load_attention_map(image_path: Path) -> np.ndarray:
    """
    Load an attention map from PNG file and normalize to 0-1.
    
    Args:
        image_path: Path to the PNG attention map
        
    Returns:
        Normalized attention map as numpy array
    """
    if not image_path.exists():
        raise FileNotFoundError(f"Attention map not found: {image_path}")
    
    # Load as grayscale
    img = Image.open(image_path).convert('L')
    # Convert to numpy array and normalize to 0-1
    attention_map = np.array(img, dtype=np.float32) / 255.0
    
    return attention_map


def blur_attention_map(attention_map: np.ndarray, blur_method: str = "gaussian", 
                      blur_strength: float = 1.0) -> np.ndarray:
    """
    Apply blurring to an attention map.
    
    Args:
        attention_map: Input attention map (0-1 normalized)
        blur_method: Type of blur ("gaussian", "uniform", "median")
        blur_strength: Strength of blur (sigma for gaussian, radius for others)
        
    Returns:
        Blurred attention map
    """
    if blur_method == "gaussian":
        # Gaussian blur using scipy
        blurred = ndimage.gaussian_filter(attention_map, sigma=blur_strength)
    elif blur_method == "uniform":
        # Uniform blur (box filter)
        kernel_size = int(2 * blur_strength + 1)
        blurred = ndimage.uniform_filter(attention_map, size=kernel_size)
    elif blur_method == "median":
        # Median filter
        kernel_size = int(2 * blur_strength + 1)
        blurred = ndimage.median_filter(attention_map, size=kernel_size)
    else:
        raise ValueError(f"Unknown blur method: {blur_method}. Use 'gaussian', 'uniform', or 'median'")
    
    # Ensure values stay in [0, 1] range
    blurred = np.clip(blurred, 0, 1)
    
    return blurred


def find_common_tiles(parent_folder: Path, models: List[str], max_tiles: Optional[int] = None, simple_mode: bool = False) -> List[str]:
    """
    Find tiles that exist for all models using efficient set intersections.
    
    Args:
        parent_folder: Parent directory containing model subdirectories
        models: List of model names
        max_tiles: Maximum number of tiles to return (for testing)
        simple_mode: Whether to search in 'simple' subdirectories
        
    Returns:
        List of common tile filenames
    """
    subdir = "simple" if simple_mode else "combined"
    print(f"Finding tiles available for all {len(models)} models in '{subdir}' subdirectories...")
    
    # Get tiles for each model using set operations
    model_tile_sets = []
    
    for model in tqdm(models, desc="Scanning model directories"):
        model_dir = parent_folder / model / subdir
        if not model_dir.exists():
            print(f"Warning: Model directory not found: {model_dir}")
            continue
            
        # Get all PNG files in this model's directory
        model_tiles = {f.name for f in model_dir.glob("*.png")}
        model_tile_sets.append(model_tiles)
        print(f"  {model}: {len(model_tiles)} tiles")
    
    if not model_tile_sets:
        raise ValueError("No model directories found with tiles")
    
    # Find intersection of all model tile sets (tiles that exist for ALL models)
    print("Computing intersection of all model tile sets...")
    common_tiles = set.intersection(*model_tile_sets)
    
    # Convert to sorted list for consistent ordering
    common_tiles = sorted(list(common_tiles))
    
    print(f"Found {len(common_tiles)} tiles common to all models")
    
    # Limit to max_tiles if specified (for testing)
    if max_tiles is not None and len(common_tiles) > max_tiles:
        common_tiles = common_tiles[:max_tiles]
        print(f"Limited to first {max_tiles} tiles for testing")
    
    return common_tiles


def compute_dice_overlaps_percentile(parent_folder: Path, models: List[str], 
                                   common_tiles: List[str], percentiles: List[float] = [50.0, 60.0, 70.0, 80.0, 90.0],
                                   blur_enabled: bool = False, blur_method: str = "gaussian", 
                                   blur_strength: float = 1.0, simple_mode: bool = False) -> Dict[Tuple[str, str, float], List[float]]:
    """
    Compute Dice score overlaps between all model pairs using percentile-based thresholding.
    
    Args:
        parent_folder: Parent directory containing model subdirectories
        models: List of model names
        common_tiles: List of tiles that exist for all models
        percentiles: List of percentiles to test (e.g., [50.0, 60.0, 70.0, 80.0, 90.0])
        blur_enabled: Whether to apply blurring to attention maps
        blur_method: Type of blur to apply ("gaussian", "uniform", "median")
        blur_strength: Strength of blur (sigma for gaussian, radius for others)
        simple_mode: Whether to search in 'simple' subdirectories
        
    Returns:
        Dictionary mapping (model1, model2, percentile) tuples to list of Dice scores
    """
    dice_scores = {}
    subdir = "simple" if simple_mode else "combined"
    
    # Generate all pairs of models
    model_pairs = list(itertools.combinations(models, 2))
    
    blur_info = f" with {blur_method} blur (strength={blur_strength})" if blur_enabled else ""
    print(f"Computing Dice scores for {len(model_pairs)} model pairs across {len(common_tiles)} tiles at {len(percentiles)} percentiles{blur_info}...")
    
    for model1, model2 in tqdm(model_pairs, desc="Processing model pairs"):
        for percentile in tqdm(percentiles, desc=f"{model1} vs {model2} percentiles", leave=False):
            pair_scores = []
            
            for tile_name in tqdm(common_tiles, desc=f"P{percentile:.0f}", leave=False):
                try:
                    # Load attention maps for both models
                    map1_path = parent_folder / model1 / subdir / tile_name
                    map2_path = parent_folder / model2 / subdir / tile_name
                    
                    attention1 = load_attention_map(map1_path)
                    attention2 = load_attention_map(map2_path)
                    
                    # Apply blurring if enabled
                    if blur_enabled:
                        attention1 = blur_attention_map(attention1, blur_method, blur_strength)
                        attention2 = blur_attention_map(attention2, blur_method, blur_strength)
                    
                    # Compute Dice score using percentile thresholding
                    dice = dice_score_percentile(attention1, attention2, percentile)
                    pair_scores.append(dice)
                    
                except Exception as e:
                    tqdm.write(f"Warning: Failed to process {tile_name} for {model1} vs {model2} at P{percentile:.0f}: {e}")
                    continue
            
            dice_scores[(model1, model2, percentile)] = pair_scores
            tqdm.write(f"  {model1} vs {model2} P{percentile:.0f}: {len(pair_scores)} scores (mean: {np.mean(pair_scores):.3f})")
    
    return dice_scores


def compute_dice_overlaps(parent_folder: Path, models: List[str], 
                         common_tiles: List[str], threshold: float = 0.5,
                         blur_enabled: bool = False, blur_method: str = "gaussian", 
                         blur_strength: float = 1.0, simple_mode: bool = False) -> Dict[Tuple[str, str], List[float]]:
    """
    Compute Dice score overlaps between all model pairs using fixed threshold.
    
    Args:
        parent_folder: Parent directory containing model subdirectories
        models: List of model names
        common_tiles: List of tiles that exist for all models
        threshold: Threshold for binary conversion
        blur_enabled: Whether to apply blurring to attention maps
        blur_method: Type of blur to apply ("gaussian", "uniform", "median")
        blur_strength: Strength of blur (sigma for gaussian, radius for others)
        simple_mode: Whether to search in 'simple' subdirectories
        
    Returns:
        Dictionary mapping (model1, model2) pairs to list of Dice scores
    """
    dice_scores = {}
    subdir = "simple" if simple_mode else "combined"
    
    # Generate all pairs of models
    model_pairs = list(itertools.combinations(models, 2))
    
    blur_info = f" with {blur_method} blur (strength={blur_strength})" if blur_enabled else ""
    print(f"Computing Dice scores for {len(model_pairs)} model pairs across {len(common_tiles)} tiles{blur_info}...")
    
    for model1, model2 in tqdm(model_pairs, desc="Processing model pairs"):
        pair_scores = []
        
        for tile_name in tqdm(common_tiles, desc=f"{model1} vs {model2}", leave=False):
            try:
                # Load attention maps for both models
                map1_path = parent_folder / model1 / subdir / tile_name
                map2_path = parent_folder / model2 / subdir / tile_name
                
                attention1 = load_attention_map(map1_path)
                attention2 = load_attention_map(map2_path)
                
                # Apply blurring if enabled
                if blur_enabled:
                    attention1 = blur_attention_map(attention1, blur_method, blur_strength)
                    attention2 = blur_attention_map(attention2, blur_method, blur_strength)
                
                # Compute Dice score
                dice = dice_score(attention1, attention2, threshold)
                pair_scores.append(dice)
                
            except Exception as e:
                tqdm.write(f"Warning: Failed to process {tile_name} for {model1} vs {model2}: {e}")
                continue
        
        dice_scores[(model1, model2)] = pair_scores
        tqdm.write(f"  {model1} vs {model2}: {len(pair_scores)} scores (mean: {np.mean(pair_scores):.3f})")
    
    return dice_scores


def save_dice_results_csv_percentile(dice_scores: Dict[Tuple[str, str, float], List[float]], 
                                    output_path: Path) -> None:
    """
    Save percentile-based Dice score results to CSV file.
    
    Args:
        dice_scores: Dictionary mapping (model1, model2, percentile) tuples to Dice scores
        output_path: Path to save CSV file
    """
    with open(output_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        
        # Write header
        writer.writerow(['Model1', 'Model2', 'Percentile', 'Mean_Dice', 'Std_Dice', 'Min_Dice', 'Max_Dice', 'Num_Tiles'])
        
        # Write data for each model pair and percentile
        for (model1, model2, percentile), scores in dice_scores.items():
            if scores:  # Only write if we have scores
                writer.writerow([
                    model1,
                    model2,
                    f"{percentile:.1f}",
                    f"{np.mean(scores):.4f}",
                    f"{np.std(scores):.4f}",
                    f"{np.min(scores):.4f}",
                    f"{np.max(scores):.4f}",
                    len(scores)
                ])
    
    print(f"Percentile-based Dice score results saved to: {output_path}")


def save_dice_results_csv(dice_scores: Dict[Tuple[str, str], List[float]], 
                         output_path: Path) -> None:
    """
    Save Dice score results to CSV file.
    
    Args:
        dice_scores: Dictionary mapping model pairs to Dice scores
        output_path: Path to save CSV file
    """
    with open(output_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        
        # Write header
        writer.writerow(['Model1', 'Model2', 'Mean_Dice', 'Std_Dice', 'Min_Dice', 'Max_Dice', 'Num_Tiles'])
        
        # Write data for each model pair
        for (model1, model2), scores in dice_scores.items():
            if scores:  # Only write if we have scores
                writer.writerow([
                    model1,
                    model2,
                    f"{np.mean(scores):.4f}",
                    f"{np.std(scores):.4f}",
                    f"{np.min(scores):.4f}",
                    f"{np.max(scores):.4f}",
                    len(scores)
                ])
    
    print(f"Dice score results saved to: {output_path}")


def create_attention_overlay(original_tile: np.ndarray, attention_map: np.ndarray, 
                           alpha: float = 0.6, colormap: str = 'hot') -> np.ndarray:
    """
    Create an overlay of attention map on original tile.
    
    Args:
        original_tile: Original tile image (RGB)
        attention_map: Attention map (0-1 normalized)
        alpha: Transparency of attention overlay
        colormap: Matplotlib colormap name
        
    Returns:
        Overlaid image as numpy array
    """
    # Ensure original tile is RGB
    if len(original_tile.shape) == 2:
        original_tile = np.stack([original_tile] * 3, axis=-1)
    
    # Get colormap
    cmap = cm.get_cmap(colormap)
    
    # Normalize attention map to 0-1
    norm = Normalize(vmin=0, vmax=1)
    attention_colored = cmap(norm(attention_map))
    
    # Convert to RGB (remove alpha channel)
    attention_colored = attention_colored[:, :, :3]
    
    # Create overlay
    overlay = (1 - alpha) * original_tile + alpha * attention_colored * 255
    
    return overlay.astype(np.uint8)


def generate_example_overlays(parent_folder: Path, models: List[str], 
                            common_tiles: List[str], num_examples: int = 5) -> None:
    """
    Generate example overlays for each model using random tiles.
    
    Args:
        parent_folder: Parent directory containing model subdirectories
        models: List of model names
        common_tiles: List of tiles that exist for all models
        num_examples: Number of random examples to generate
    """
    # Select random tiles
    if len(common_tiles) < num_examples:
        selected_tiles = common_tiles
        print(f"Warning: Only {len(common_tiles)} tiles available, using all of them")
    else:
        selected_tiles = random.sample(common_tiles, num_examples)
    
    print(f"Generating overlays for {len(selected_tiles)} random tiles...")
    
    for model in tqdm(models, desc="Generating overlays"):
        for i, tile_name in enumerate(tqdm(selected_tiles, desc=f"{model} overlays", leave=False)):
            try:
                # Load original tile
                original_path = parent_folder / "Original" / tile_name
                original_img = Image.open(original_path).convert('RGB')
                original_array = np.array(original_img)
                
                # Load attention map
                attention_path = parent_folder / model / "combined" / tile_name
                attention_map = load_attention_map(attention_path)
                
                # Create overlay
                overlay = create_attention_overlay(original_array, attention_map)
                
                # Save overlay
                overlay_img = Image.fromarray(overlay)
                output_path = parent_folder / f"{model}_overlay_example_{i+1}.png"
                overlay_img.save(output_path, dpi=(300, 300))
                
                tqdm.write(f"  Saved: {output_path}")
                
            except Exception as e:
                tqdm.write(f"Warning: Failed to create overlay for {model} - {tile_name}: {e}")
                continue


def create_dice_heatmap_percentile(dice_scores: Dict[Tuple[str, str, float], List[float]], 
                                  output_path: Path) -> None:
    """
    Create a heatmap visualization of percentile-based Dice scores.
    
    Args:
        dice_scores: Dictionary mapping (model1, model2, percentile) tuples to Dice scores
        output_path: Path to save heatmap
    """
    models = sorted(set([model for (model1, model2, _) in dice_scores.keys() for model in [model1, model2]]))
    percentiles = sorted(set([p for (_, _, p) in dice_scores.keys()]))
    
    # Create subplot grid for each percentile
    n_percentiles = len(percentiles)
    fig, axes = plt.subplots(1, n_percentiles, figsize=(5 * n_percentiles, 5))
    if n_percentiles == 1:
        axes = [axes]
    
    for idx, percentile in enumerate(percentiles):
        # Create matrix for this percentile
        n_models = len(models)
        dice_matrix = np.zeros((n_models, n_models))
        
        # Fill diagonal with 1.0 (perfect overlap with self)
        np.fill_diagonal(dice_matrix, 1.0)
        
        # Fill off-diagonal with mean Dice scores for this percentile
        for (model1, model2, p), scores in dice_scores.items():
            if p == percentile and scores:
                i1 = models.index(model1)
                i2 = models.index(model2)
                mean_dice = np.mean(scores)
                dice_matrix[i1, i2] = mean_dice
                dice_matrix[i2, i1] = mean_dice  # Symmetric
        
        # Create heatmap for this percentile
        sns.heatmap(dice_matrix, 
                    xticklabels=models, 
                    yticklabels=models,
                    annot=True, 
                    fmt='.3f',
                    cmap='viridis',
                    cbar_kws={'label': 'Dice Score'},
                    ax=axes[idx])
        
        axes[idx].set_title(f'{percentile:.0f}th Percentile')
        axes[idx].set_xlabel('Model')
        axes[idx].set_ylabel('Model')
    
    plt.suptitle('Attention Map Overlap (Dice Scores) Between Foundation Models by Percentile', fontsize=14)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Percentile-based Dice score heatmap saved to: {output_path}")


def create_dice_heatmap(dice_scores: Dict[Tuple[str, str], List[float]], 
                       output_path: Path) -> None:
    """
    Create a heatmap visualization of Dice scores.
    
    Args:
        dice_scores: Dictionary mapping model pairs to Dice scores
        output_path: Path to save heatmap
    """
    models = sorted(set([model for pair in dice_scores.keys() for model in pair]))
    
    # Create matrix for heatmap
    n_models = len(models)
    dice_matrix = np.zeros((n_models, n_models))
    
    # Fill diagonal with 1.0 (perfect overlap with self)
    np.fill_diagonal(dice_matrix, 1.0)
    
    # Fill off-diagonal with mean Dice scores
    for (model1, model2), scores in dice_scores.items():
        if scores:
            i1 = models.index(model1)
            i2 = models.index(model2)
            mean_dice = np.mean(scores)
            dice_matrix[i1, i2] = mean_dice
            dice_matrix[i2, i1] = mean_dice  # Symmetric
    
    # Create heatmap
    plt.figure(figsize=(10, 8))
    sns.heatmap(dice_matrix, 
                xticklabels=models, 
                yticklabels=models,
                annot=True, 
                fmt='.3f',
                cmap='viridis',
                cbar_kws={'label': 'Dice Score'})
    
    plt.title('Attention Map Overlap (Dice Scores) Between Foundation Models')
    plt.xlabel('Model')
    plt.ylabel('Model')
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Dice score heatmap saved to: {output_path}")


def main():
    """Main function to compute attention overlaps."""
    parser = argparse.ArgumentParser(
        description="Compute Dice score overlaps between attention maps from different foundation models"
    )
    parser.add_argument(
        "--parent-folder", "-p",
        type=str,
        required=True,
        help="Path to parent folder containing model subdirectories and Original folder"
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Threshold for converting attention maps to binary masks (default: 0.5)"
    )
    parser.add_argument(
        "--percentile-mode",
        action="store_true",
        help="Use percentile-based thresholding instead of fixed threshold"
    )
    parser.add_argument(
        "--percentiles",
        type=float,
        nargs='+',
        default=[50.0, 60.0, 70.0, 80.0, 90.0],
        help="Percentiles to test when using percentile mode (default: 50.0 60.0 70.0 80.0 90.0)"
    )
    parser.add_argument(
        "--num-examples",
        type=int,
        default=5,
        help="Number of random example overlays to generate per model (default: 5)"
    )
    parser.add_argument(
        "--colormap",
        type=str,
        default="hot",
        help="Colormap for attention overlays (default: hot)"
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Test mode: only process first 1000 tiles for faster execution"
    )
    parser.add_argument(
        "--blur",
        action="store_true",
        help="Apply blurring to attention maps before computing Dice scores"
    )
    parser.add_argument(
        "--blur-method",
        type=str,
        default="gaussian",
        choices=["gaussian", "uniform", "median"],
        help="Blur method to use when --blur is enabled (default: gaussian)"
    )
    parser.add_argument(
        "--blur-strength",
        type=float,
        default=1.0,
        help="Blur strength (sigma for gaussian, radius for others) when --blur is enabled (default: 1.0)"
    )
    parser.add_argument(
        "--simple",
        action="store_true",
        help="Search for attention maps in 'simple' subdirectories (from --simple mode in extract_attention_maps.py)"
    )
    
    args = parser.parse_args()
    
    # Convert to Path objects
    parent_folder = Path(args.parent_folder)
    
    if not parent_folder.exists():
        raise FileNotFoundError(f"Parent folder not found: {parent_folder}")
    
    # Define the 5 foundation models
    models = ["musk", "conch_v15", "virchow2", "hoptimus1", "gigapath"]
    
    print(f"Analyzing attention maps in: {parent_folder}")
    print(f"Models: {', '.join(models)}")
    if args.test:
        print("TEST MODE: Processing only first 1000 tiles")
    if args.blur:
        print(f"BLUR MODE: Applying {args.blur_method} blur (strength={args.blur_strength})")
    if args.percentile_mode:
        print(f"PERCENTILE MODE: Testing percentiles {args.percentiles}")
    else:
        print(f"FIXED THRESHOLD MODE: Using threshold {args.threshold}")
    if args.simple:
        print("SIMPLE MODE: Searching in 'simple' subdirectories")
    
    # Check that all model directories exist
    missing_models = []
    for model in models:
        model_dir = parent_folder / model
        if not model_dir.exists():
            missing_models.append(model)
    
    if missing_models:
        print(f"Warning: Missing model directories: {missing_models}")
        models = [m for m in models if m not in missing_models]
    
    if len(models) < 2:
        raise ValueError("Need at least 2 models to compute overlaps")
    
    print(f"Using models: {', '.join(models)}")
    
    # Find common tiles
    print("\nFinding common tiles...")
    max_tiles = 1000 if args.test else None
    common_tiles = find_common_tiles(parent_folder, models, max_tiles, args.simple)
    print(f"Found {len(common_tiles)} tiles common to all models")
    
    if len(common_tiles) == 0:
        raise ValueError("No common tiles found across all models")
    
    # Compute Dice overlaps
    if args.percentile_mode:
        print(f"\nComputing Dice scores with percentiles {args.percentiles}...")
        dice_scores = compute_dice_overlaps_percentile(
            parent_folder, models, common_tiles, args.percentiles,
            blur_enabled=args.blur, blur_method=args.blur_method, blur_strength=args.blur_strength,
            simple_mode=args.simple
        )
        
        # Save results to CSV
        csv_path = parent_folder / "attention_overlap_dice_scores_percentile.csv"
        save_dice_results_csv_percentile(dice_scores, csv_path)
        
        # Create heatmap visualization
        heatmap_path = parent_folder / "attention_overlap_heatmap_percentile.png"
        create_dice_heatmap_percentile(dice_scores, heatmap_path)
    else:
        print(f"\nComputing Dice scores with threshold {args.threshold}...")
        dice_scores = compute_dice_overlaps(
            parent_folder, models, common_tiles, args.threshold,
            blur_enabled=args.blur, blur_method=args.blur_method, blur_strength=args.blur_strength,
            simple_mode=args.simple
        )
        
        # Save results to CSV
        csv_path = parent_folder / "attention_overlap_dice_scores.csv"
        save_dice_results_csv(dice_scores, csv_path)
        
        # Create heatmap visualization
        heatmap_path = parent_folder / "attention_overlap_heatmap.png"
        create_dice_heatmap(dice_scores, heatmap_path)
    
    # Generate example overlays
    print(f"\nGenerating {args.num_examples} example overlays per model...")
    generate_example_overlays(parent_folder, models, common_tiles, args.num_examples)
    
    print("\nAnalysis complete!")
    print(f"Results saved in: {parent_folder}")
    print(f"  - Dice scores CSV: {csv_path}")
    print(f"  - Heatmap visualization: {heatmap_path}")
    print(f"  - Example overlays: {args.num_examples} per model")


if __name__ == "__main__":
    main()
